### ISSUE TITLE
Creating a Live Text state

### ISSUE THREAD

**Issue by davidjumbi** [brightsign/BrightAuthor-Plugins#1]
hi,
I have successfully followed all the steps(1-7) provided  to add an RSS Feed and Parser Script from this page https://github.com/brightsign/BrightAuthor-Parser-Scripts/tree/master/RSS-Converter , however I cant get the last bit to work i.e 
"Now you can create a Live Text state that displays RSS items by index. Under Type, choose Live Text Data and select the feed you just added. Then specify the Item index as desired"

I tried following the instructions to add a new live text (http://www.brightsign.biz/documents/BrightAuthor_UserGuide_2.3.pdf) but still it got me know wea

would really appreciate it if I could get some help on how to proceed from step 7 above (i.e steps of Adding the RSS Feed and Parser Script)

thanks

**Comment by bhastings1019** [comment]
Closing for now. If active, please reference this Github issue in a Support Ticket opened with BrightSign by emailing, support@brightsig.biz.
